"""Learning memory: write insights from feedback to persistent storage.

The learnings.md file is included in Claude's context for future
comment generation, so the agent literally learns from its mistakes.
"""

from datetime import datetime

from src.config import LEARNINGS_PATH
from src.db import get_connection
from src.log import get_logger

log = get_logger("learning")


def update_learnings(feedback_results: dict) -> None:
    """Analyze feedback results and write new learnings.

    Appends to data/learnings.md with dated entries grouped by subreddit.
    """
    if not feedback_results.get("karma_changes") and feedback_results.get("removed", 0) == 0:
        return

    today = datetime.utcnow().strftime("%Y-%m-%d")
    entries = []

    # Analyze karma changes
    for change in feedback_results.get("karma_changes", []):
        sub = change["subreddit"]
        delta = change["delta"]
        if delta >= 5:
            entries.append(
                f"## {today} — r/{sub}\n"
                f"- Comment got +{delta} karma. What worked: check the comment in DB for style reference.\n"
            )
        elif delta <= -3:
            # Get the comment text for analysis
            comment_text = _get_comment_text(change["comment_id"])
            entries.append(
                f"## {today} — r/{sub}\n"
                f"- Comment got {delta} karma. Possible issues: tone mismatch or off-topic. "
                f"Comment snippet: \"{comment_text[:100]}...\"\n"
            )

    # Analyze removals
    if feedback_results.get("removed", 0) > 0:
        removed_comments = _get_recently_removed()
        for rc in removed_comments:
            entries.append(
                f"## {today} — r/{rc['subreddit']}\n"
                f"- Comment removed by mods. Snippet: \"{rc['text'][:100]}...\"\n"
                f"- Lesson: this type of content gets removed in r/{rc['subreddit']}. Avoid similar framing.\n"
            )

    # Analyze shadowbans
    if feedback_results.get("shadowbanned", 0) > 0:
        entries.append(
            f"## {today} — CRITICAL\n"
            f"- Shadowban detected! Account may be compromised. Review posting patterns.\n"
        )

    if entries:
        _append_learnings(entries)
        log.info(f"Added {len(entries)} new learning entries")


def generate_subreddit_summary(subreddit_name: str) -> str:
    """Generate a summary of learnings for a specific subreddit.

    Returns a condensed version suitable for including in prompts.
    """
    if not LEARNINGS_PATH.exists():
        return ""

    content = LEARNINGS_PATH.read_text()
    lines = content.split("\n")

    relevant = []
    capturing = False
    for line in lines:
        if f"r/{subreddit_name}" in line:
            capturing = True
        elif capturing and line.startswith("## "):
            capturing = False
        if capturing:
            relevant.append(line)

    if not relevant:
        return ""

    # Return most recent 10 entries
    return "\n".join(relevant[-30:])


def _get_comment_text(comment_id: str) -> str:
    """Get comment text from DB."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT comment_text FROM comments WHERE id = ?",
            (comment_id,),
        ).fetchone()
        return row[0] if row else ""


def _get_recently_removed() -> list[dict]:
    """Get recently removed comments from DB."""
    today = datetime.utcnow().strftime("%Y-%m-%d")
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT subreddit, comment_text as text FROM comments
               WHERE status = 'removed' AND posted_at >= ?""",
            (today,),
        ).fetchall()
        return [dict(r) for r in rows]


def _append_learnings(entries: list[str]) -> None:
    """Append learning entries to the learnings file."""
    LEARNINGS_PATH.parent.mkdir(parents=True, exist_ok=True)

    existing = ""
    if LEARNINGS_PATH.exists():
        existing = LEARNINGS_PATH.read_text()

    if not existing:
        existing = "# Reddit Agent Learnings\n\nThis file is auto-generated by the feedback loop. It captures what works and what doesn't across subreddits.\n\n"

    new_content = existing + "\n" + "\n".join(entries)

    # Keep file under a reasonable size (last 200 entries)
    lines = new_content.split("\n")
    if len(lines) > 1000:
        # Keep header (first 4 lines) + last 800 lines
        new_content = "\n".join(lines[:4] + ["", "... (older entries trimmed)", ""] + lines[-800:])

    LEARNINGS_PATH.write_text(new_content)
